import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import MainScene from "@/features/layouts/Three/MainScene";
import dynamic from "next/dynamic";
import * as Layout from "@/features/layouts";
import SmoothScroller from "@/features/layouts/SmoothScroller";
import MainCanvas from "@/features/layouts/Three/MainCanvas";
import MainScene from "@/features/layouts/Three/MainScene";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} scrollbar-hidden font-sans text-lg antialiased`}
      >
        <MainCanvas className="fixed top-0" />
        <Layout.Header />
        <Layout.ScrollProgressBar />
        <SmoothScroller />
        {children}
        <Layout.ContactSection />
      </body>
    </html>
  );
}
